# Generated by Django 4.2.7 on 2025-07-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('credential_url', models.URLField(blank=True, default='')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start_year']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='personalinfo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={},
        ),
        migrations.RemoveField(
            model_name='education',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='education',
            name='cgpa',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='experience',
            name='achievements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='github_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='leetcode_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='achievements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(default='Computer Science', max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='leetcode_problems',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='location',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='years_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='portfolio.technology'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('languages', 'Languages'), ('frameworks', 'Frameworks/Technologies'), ('aiml', 'AI/ML'), ('databases', 'Databases'), ('devops', 'DevOps'), ('cloud', 'Cloud & Tools'), ('concepts', 'Concepts')], max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='technology',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
